/**
 * Sync vendored artifacts from sibling packages into this extension.
 */
import { copyFileSync, mkdirSync, existsSync, readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = dirname(fileURLToPath(import.meta.url));
const vendor = resolve(__dirname, 'vendor');
mkdirSync(vendor, { recursive: true });

const corePkg = resolve(__dirname, '../soma-assist-core');
const guidePkg = resolve(__dirname, '../soma-guide');

/* Build core if needed */
if (!existsSync(resolve(corePkg, 'dist/soma-assist-core.js'))) {
  execSync('npm run build', { cwd: corePkg, stdio: 'inherit' });
} else {
  try { execSync('npm run build', { cwd: corePkg, stdio: 'inherit' }); } catch (e) {}
}

copyFileSync(resolve(corePkg, 'dist/soma-assist-core.js'), resolve(vendor, 'soma-assist-core.js'));
copyFileSync(resolve(corePkg, 'dist/soma-assist-core.css'), resolve(vendor, 'soma-assist-core.css'));
copyFileSync(resolve(guidePkg, 'soma-guide.js'), resolve(vendor, 'soma-guide.js'));
copyFileSync(resolve(guidePkg, 'soma-guide.css'), resolve(vendor, 'soma-guide.css'));

/* Inline guide CSS as a JS string for shadow injection (content-script safe). */
const guideCss = readFileSync(resolve(vendor, 'soma-guide.css'), 'utf8');
const cssModule = `/* auto-generated by sync.mjs — do not edit */\nwindow.__ADRIAN_GUIDE_CSS__ = ${JSON.stringify(guideCss)};\n`;
writeFileSync(resolve(vendor, 'soma-guide-css.js'), cssModule, 'utf8');

console.log('adrian-extension vendor synced:');
console.log('  soma-assist-core.js/css');
console.log('  soma-guide.js/css + soma-guide-css.js');
