// Provisioning planner. Turns a scaffolded Soma app into live infra — but safely:
// it EMITS an ordered, reviewable `provision.sh` (and prints the plan). It does not
// create anything itself. Secrets are referenced as ${ENV_VARS}, never inlined.
//
// The generated script is push-to-rebuild: create repo -> push -> create+link
// Netlify site -> set env -> connect for CD -> apply Supabase SQL. Each step is
// guarded and echoes what it's doing so the human can watch (the dark-factory glass
// wall, in script form).

import { writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

function shEsc(s) { return String(s).replace(/'/g, "'\\''"); }

// Returns { script, steps[], warnings[] } for a scaffolded app dir.
export function planProvision(doc, { appDir } = {}) {
  const app = doc.soma_app;
  const a = app.affordances;
  const slug = app.slug;
  const repo = app.targets.repo || `github.com/<org>/${slug}-soma`;
  const repoSlug = repo.replace(/^https?:\/\//, "").replace(/^github\.com\//, "");
  const site = app.targets.netlify_site || `${slug}-soma`;
  const needsBackend = a.changelog?.enabled || a.feedback?.enabled || a.identity?.enabled || a.intake?.enabled;
  const sharedApp = app.targets.supabase?.app_project?.shared;

  const steps = [];
  const warnings = [];
  const L = [];
  const p = (...x) => L.push(...x);

  p(`#!/usr/bin/env bash`);
  p(`# Provision ${app.name} (${slug}). Generated by soma-scaffolder.`);
  p(`# Review before running. Re-runnable: each step checks for existing resources.`);
  p(`# Secrets come from your environment — none are written into this file.`);
  p(`set -euo pipefail`);
  p(``);
  p(`echo "▶ Provisioning ${slug} — repo=${repoSlug} site=${site}"`);
  p(``);

  // 1. Preconditions
  steps.push("check CLIs");
  p(`# --- 0. preconditions ---`);
  p(`for c in git gh netlify; do command -v "$c" >/dev/null || { echo "missing CLI: $c"; exit 1; }; done`);
  if (needsBackend) p(`command -v supabase >/dev/null || echo "note: supabase CLI not found — you'll apply sql/schema.sql via the dashboard"`);
  p(``);

  // 2. Repo
  steps.push("create + push repo");
  p(`# --- 1. git repo (push-to-rebuild) ---`);
  p(`cd '${shEsc(appDir || ".")}'`);
  p(`[ -d .git ] || git init -q`);
  p(`git add -A && git commit -q -m "scaffold ${slug}" || echo "  (nothing to commit)"`);
  p(`if ! gh repo view '${repoSlug}' >/dev/null 2>&1; then`);
  p(`  gh repo create '${repoSlug}' --private --source . --remote origin --push`);
  p(`else`);
  p(`  git remote get-url origin >/dev/null 2>&1 || git remote add origin "https://github.com/${repoSlug}.git"`);
  p(`  git push -u origin HEAD`);
  p(`fi`);
  p(``);

  // 3. Netlify site + connect for CD
  steps.push("create + link Netlify site, connect CD");
  p(`# --- 2. netlify site (CD from the repo) ---`);
  p(`if ! netlify sites:list --json 2>/dev/null | grep -q '"name": *"${site}"'; then`);
  p(`  netlify sites:create --name '${site}' || echo "  (name may be taken; adjust targets.netlify_site)"`);
  p(`fi`);
  p(`netlify link --name '${site}'`);
  p(`# Connect the GitHub repo for push-to-rebuild (one-time; UI or API):`);
  p(`echo "  → In Netlify, connect ${repoSlug} so pushes to the default branch deploy."`);
  p(``);

  // 4. Env vars
  if (needsBackend) {
    steps.push("set Netlify env vars");
    p(`# --- 3. netlify env (secrets from your shell env) ---`);
    p(`: "\${SUPABASE_URL:?set SUPABASE_URL in your env}"`);
    p(`: "\${SUPABASE_SERVICE_ROLE_KEY:?set SUPABASE_SERVICE_ROLE_KEY in your env}"`);
    p(`netlify env:set SUPABASE_URL "$SUPABASE_URL"`);
    p(`netlify env:set SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"`);
    if (a.feedback?.enabled) {
      p(`[ -n "\${OWNER_EMAIL:-}" ] && netlify env:set OWNER_EMAIL "$OWNER_EMAIL" || true`);
      p(`[ -n "\${ASSISTANT_ID:-}" ] && netlify env:set ASSISTANT_ID "$ASSISTANT_ID" || true`);
    }
    p(``);
  } else {
    warnings.push("no backend affordances enabled — skipping Supabase env + SQL");
  }

  // 5. Supabase SQL
  if (needsBackend) {
    steps.push("apply Supabase schema");
    p(`# --- 4. supabase schema (idempotent) ---`);
    p(`# soma_profiles (identity) belongs to the SHARED SOMA project — do not recreate it per app.`);
    p(`if command -v supabase >/dev/null && [ -f sql/schema.sql ]; then`);
    p(`  echo "  → run sql/schema.sql against the ${sharedApp ? "shared" : "app"} project (supabase db execute or psql)"`);
    p(`else`);
    p(`  echo "  → open the Supabase SQL editor and run sql/schema.sql"`);
    p(`fi`);
    p(``);
    warnings.push("soma_profiles lives in the shared SOMA project — confirm you are not duplicating it");
  }

  // 6. Deploy
  steps.push("trigger first deploy");
  p(`# --- 5. first deploy ---`);
  p(`git push origin HEAD   # push-to-rebuild`);
  p(`echo "✓ ${slug} provisioned. Preview the deploy in Netlify."`);

  return { script: L.join("\n") + "\n", steps, warnings, repoSlug, site };
}

// Writes provision.sh into the app dir (dry-run default). Returns the plan.
export function provision(doc, { appDir, execute = false } = {}) {
  if (!appDir) appDir = join(process.cwd(), `${doc.soma_app.slug}-soma`);
  if (!existsSync(appDir)) throw new Error(`app dir not found: ${appDir} (scaffold first)`);
  const plan = planProvision(doc, { appDir });
  const scriptPath = join(appDir, "provision.sh");
  writeFileSync(scriptPath, plan.script, { mode: 0o755 });
  return { ...plan, scriptPath, executed: false, execute };
}
