'use strict';

/**
 * Unit tests for converter.js
 * - pageNodeToYeshieFragment: PageNode → Yeshie site.model.json shape
 * - yeshieFragmentToSomaConfig: Yeshie fragment → SomaGuideConfig
 * - roundTrip: full chain, both outputs
 */

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');
const { JSDOM } = require('jsdom');

const AutoMapper = require('../auto-mapper.js');
const Converter  = require('../converter.js');

/* ── Shared fixture pageNode ─────────────────────────────────────────────── */
function makePageNode() {
  const dom = new JSDOM(`<!DOCTYPE html>
<html>
<head>
  <title>Test Admin App</title>
  <meta name="description" content="Manage your team.">
</head>
<body class="v-application">
  <header>
    <nav>
      <a href="/home" aria-label="Home">Home</a>
      <a href="/users" aria-label="Users">Users</a>
      <a href="/settings" aria-label="Settings">Settings</a>
    </nav>
  </header>
  <main role="main">
    <h1>Dashboard</h1>
    <h2>Users</h2>
    <button aria-label="Add User">Add User</button>
    <input placeholder="Search users" aria-label="Search users" type="search">
  </main>
</body>
</html>`, { url: 'https://test-admin.example.com/overview' });
  return AutoMapper.perceive(dom.window.document, dom.window);
}

/* ── pageNodeToYeshieFragment ────────────────────────────────────────────── */

describe('pageNodeToYeshieFragment', () => {
  let pageNode, steps, fragment;

  test('produces a fragment with correct _meta fields', () => {
    pageNode  = makePageNode();
    steps     = AutoMapper.generateSteps(pageNode, 'Ariadne');
    fragment  = Converter.pageNodeToYeshieFragment(pageNode, steps);
    assert.ok(fragment._meta, '_meta present');
    assert.equal(fragment._meta.layer, 3);
    assert.equal(fragment._meta.site, 'test-admin.example.com');
    assert.ok(fragment._meta.autoGenerated, 'autoGenerated flag set');
    assert.ok(fragment._meta.archetypeGuess, 'archetypeGuess set');
  });

  test('stateGraph has exactly one node keyed by page path', () => {
    const nodes = fragment.stateGraph.nodes;
    const keys  = Object.keys(nodes);
    assert.equal(keys.length, 1);
    const node = nodes[keys[0]];
    assert.ok(node.description && node.description.length > 0);
    assert.ok(Array.isArray(node.signals));
  });

  test('abstractTargets keyed by slug of affordance name', () => {
    const targets = fragment.abstractTargets;
    assert.ok(Object.keys(targets).length > 0, 'abstractTargets non-empty');
    /* Every target should have role + name_contains in match */
    Object.values(targets).forEach(function (t) {
      assert.ok(t.match, 'match field present');
      assert.ok(t.match.role, 'match.role present');
    });
  });

  test('abstractTargets include anchors from co-selectors', () => {
    const targets = fragment.abstractTargets;
    const addUser = Object.values(targets).find(t => t.description.includes('Add User'));
    assert.ok(addUser, 'Add User target found');
    assert.ok(addUser.anchors && addUser.anchors.ariaLabel === 'Add User',
      'ariaLabel anchor set');
  });

  test('navigation extracted from link affordances', () => {
    assert.ok(Array.isArray(fragment.navigation));
    const home = fragment.navigation.find(n => n.text === 'Home');
    assert.ok(home, 'Home nav entry');
    assert.equal(home.href, '/home');
  });

  test('pages snapshot includes buttons and inputs', () => {
    const keys = Object.keys(fragment.pages);
    assert.equal(keys.length, 1);
    const page = fragment.pages[keys[0]];
    assert.ok(Array.isArray(page.buttons), 'buttons array');
    assert.ok(Array.isArray(page.inputs), 'inputs array');
    assert.ok(page.buttons.includes('Add User'), 'Add User in buttons');
  });

  test('walkthroughAnnotations match generated steps', () => {
    assert.ok(Array.isArray(fragment.walkthroughAnnotations));
    assert.equal(fragment.walkthroughAnnotations.length, steps.length);
    assert.equal(fragment.walkthroughAnnotations[0].id, 'intro');
  });
});

/* ── yeshieFragmentToSomaConfig ──────────────────────────────────────────── */

describe('yeshieFragmentToSomaConfig', () => {
  let fragment, somaConfig;

  test('produces a SomaGuideConfig with persona, walkthroughs, siteMap', () => {
    const pageNode = makePageNode();
    const steps    = AutoMapper.generateSteps(pageNode, 'Ariadne');
    fragment       = Converter.pageNodeToYeshieFragment(pageNode, steps);
    somaConfig     = Converter.yeshieFragmentToSomaConfig(fragment, { name: 'Ariadne', avatar: '🧵' });

    assert.ok(somaConfig.persona, 'persona present');
    assert.equal(somaConfig.persona.name, 'Ariadne');
    assert.ok(Array.isArray(somaConfig.walkthroughs));
    assert.equal(somaConfig.walkthroughs.length, 1);
    assert.equal(somaConfig.walkthroughs[0].id, 'auto-tour');
    assert.ok(somaConfig.siteMap && somaConfig.siteMap.length === 1);
  });

  test('steps round-trip: count matches original walkthroughAnnotations', () => {
    const reconSteps = somaConfig.walkthroughs[0].steps;
    assert.equal(reconSteps.length, fragment.walkthroughAnnotations.length);
  });

  test('each step has id, label, narration, instruction', () => {
    somaConfig.walkthroughs[0].steps.forEach(function (s) {
      assert.ok(s.id, 'id');
      assert.ok(s.label, 'label');
      assert.ok(typeof s.narration === 'string', 'narration');
      assert.ok(typeof s.instruction === 'string', 'instruction');
    });
  });

  test('siteMap entry has id, url, title, archetype', () => {
    const entry = somaConfig.siteMap[0];
    /* id comes from hostname(pageNode.url) — pageNode.url is populated from win.location.href */
    assert.ok(entry.id && entry.id.length > 0, 'siteMap id present: ' + entry.id);
    assert.ok(entry.title && entry.title.length > 0, 'title present');
    assert.ok(entry.archetype && entry.archetype.length > 0, 'archetype present');
  });

  test('fallback greet step added when walkthroughAnnotations is empty', () => {
    const emptyFrag = { _meta: { site: 'empty.example.com', name: 'Empty', archetypeGuess: 'generic' },
      walkthroughAnnotations: [], stateGraph: { nodes: {} }, navigation: [] };
    const cfg = Converter.yeshieFragmentToSomaConfig(emptyFrag);
    assert.equal(cfg.walkthroughs[0].steps.length, 1);
    assert.equal(cfg.walkthroughs[0].steps[0].id, 'greet');
  });
});

/* ── roundTrip ───────────────────────────────────────────────────────────── */

describe('roundTrip', () => {
  test('returns both fragment and somaConfig', () => {
    const pageNode = makePageNode();
    const result   = Converter.roundTrip(pageNode, { name: 'Ariadne', avatar: '🧵' });
    assert.ok(result.fragment, 'fragment present');
    assert.ok(result.somaConfig, 'somaConfig present');
  });

  test('roundTrip somaConfig has the same step count as direct pageNodeToSomaConfig', () => {
    const pageNode  = makePageNode();
    const persona   = { name: 'Ariadne', avatar: '🧵', greeting: 'Hi!' };
    const direct    = Converter.pageNodeToSomaConfig(pageNode, persona);
    const rt        = Converter.roundTrip(pageNode, persona);
    assert.equal(
      rt.somaConfig.walkthroughs[0].steps.length,
      direct.walkthroughs[0].steps.length,
      'step counts match through both paths'
    );
  });

  test('fragment _meta.layer === 3', () => {
    const pageNode = makePageNode();
    const { fragment } = Converter.roundTrip(pageNode);
    assert.equal(fragment._meta.layer, 3);
  });
});

/* ── pageNodeToSomaConfig (direct path) ──────────────────────────────────── */

describe('pageNodeToSomaConfig (direct)', () => {
  test('produces a valid SomaGuideConfig without going through Yeshie format', () => {
    const pageNode = makePageNode();
    const persona  = { name: 'Ariadne', avatar: '🧵', greeting: 'Hi!', shortGreeting: 'Hi?' };
    const cfg = Converter.pageNodeToSomaConfig(pageNode, persona);
    assert.equal(cfg.persona.name, 'Ariadne');
    assert.ok(cfg.walkthroughs[0].steps.length >= 2);
    /* pageNode.url is populated from win.location.href in jsdom context */
    assert.ok(cfg.siteMap && cfg.siteMap.length === 1, 'siteMap present');
    assert.ok(cfg.siteMap[0].url && typeof cfg.siteMap[0].url === 'string', 'url is a string: ' + cfg.siteMap[0].url);
  });
});
